pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Pobierz kod źródłowy z repozytorium
                git 'https://github.com/user/repo.git'
            }
        }

        stage('Deploy') {
            steps {
                // Wywołaj playbook Ansible na lokalnych VMkach
                ansiblePlaybook playbook: 'deploy.yml', inventory: 'inventory.ini'
            }
        }

        stage('Test') {
            steps {
                // Wykonaj testy automatyczne
                sh 'pytest'
            }
        }

        stage('Reports') {
            steps {
                // Wygeneruj raporty testowe
                junit 'test-results.xml'
            }
        }
    }
}