- name: Transfer file to remote machine
  hosts: myVM
  gather_facts: false
  
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/test/Jenkins_build
        state: directory
        mode: '0755'

    - name: Find out playbook's path
      shell: pwd
      register: playbook_path_output

    - debug: var=playbook_path_output.stdout

    - name: Copy file to remote machine
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/builder/backend.tar
        dest: /home/test/Jenkins_build/
        remote_src: yes
